[package]
name = "rustboy"
version = "0.1.5"
authors = ["Jonathan Dahan <jonathan@jonathan.is>"]

[dependencies]
minifb = "0.10.1"
crc = "1.5.0"
clippy = {version = "*", optional = true}

[features]
default = []

[profile.release]
debug = true
