[package]
name = "rustboy"
version = "0.1.4"
authors = ["Jonathan Dahan <jonathan@jonathan.is>"]

[dependencies]
minifb = "0.9.1"
crc = "1.4.0"
clippy = {version = "*", optional = true}

[features]
default = []

[profile.release]
debug = true
